name: second workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code from repo
        # using a pre-defined actions from the marketplace for cloning the repo to the remote machine
        uses: actions/checkout@v6
      
      - name: Install Nodejs
        uses: actions/setup-node@v6
        with:
          node_version: latest

      - name: Install Dependencies
        run: npm ci # safe version of lock install
      
      - name: Run tests
        run: npm test
